// Copyright (c) 2020, Oracle and/or its affiliates.
// Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1beta1 "github.com/verrazzano/verrazzano-helidon-app-operator/pkg/apis/verrazzano/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeHelidonApps implements HelidonAppInterface
type FakeHelidonApps struct {
	Fake *FakeVerrazzanoV1beta1
	ns   string
}

var helidonappsResource = schema.GroupVersionResource{Group: "verrazzano.io", Version: "v1beta1", Resource: "helidonapps"}

var helidonappsKind = schema.GroupVersionKind{Group: "verrazzano.io", Version: "v1beta1", Kind: "HelidonApp"}

// Get takes name of the helidonApp, and returns the corresponding helidonApp object, and an error if there is any.
func (c *FakeHelidonApps) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta1.HelidonApp, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(helidonappsResource, c.ns, name), &v1beta1.HelidonApp{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.HelidonApp), err
}

// List takes label and field selectors, and returns the list of HelidonApps that match those selectors.
func (c *FakeHelidonApps) List(ctx context.Context, opts v1.ListOptions) (result *v1beta1.HelidonAppList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(helidonappsResource, helidonappsKind, c.ns, opts), &v1beta1.HelidonAppList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1beta1.HelidonAppList{ListMeta: obj.(*v1beta1.HelidonAppList).ListMeta}
	for _, item := range obj.(*v1beta1.HelidonAppList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested helidonApps.
func (c *FakeHelidonApps) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(helidonappsResource, c.ns, opts))

}

// Create takes the representation of a helidonApp and creates it.  Returns the server's representation of the helidonApp, and an error, if there is any.
func (c *FakeHelidonApps) Create(ctx context.Context, helidonApp *v1beta1.HelidonApp, opts v1.CreateOptions) (result *v1beta1.HelidonApp, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(helidonappsResource, c.ns, helidonApp), &v1beta1.HelidonApp{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.HelidonApp), err
}

// Update takes the representation of a helidonApp and updates it. Returns the server's representation of the helidonApp, and an error, if there is any.
func (c *FakeHelidonApps) Update(ctx context.Context, helidonApp *v1beta1.HelidonApp, opts v1.UpdateOptions) (result *v1beta1.HelidonApp, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(helidonappsResource, c.ns, helidonApp), &v1beta1.HelidonApp{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.HelidonApp), err
}

// Delete takes name of the helidonApp and deletes it. Returns an error if one occurs.
func (c *FakeHelidonApps) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(helidonappsResource, c.ns, name), &v1beta1.HelidonApp{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeHelidonApps) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(helidonappsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1beta1.HelidonAppList{})
	return err
}

// Patch applies the patch and returns the patched helidonApp.
func (c *FakeHelidonApps) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.HelidonApp, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(helidonappsResource, c.ns, name, pt, data, subresources...), &v1beta1.HelidonApp{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.HelidonApp), err
}
