// Copyright (c) 2020, Oracle and/or its affiliates.
// Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

// Code generated by lister-gen. DO NOT EDIT.

package v1beta1

// HelidonAppListerExpansion allows custom methods to be added to
// HelidonAppLister.
type HelidonAppListerExpansion interface{}

// HelidonAppNamespaceListerExpansion allows custom methods to be added to
// HelidonAppNamespaceLister.
type HelidonAppNamespaceListerExpansion interface{}
