// Copyright (c) 2020, Oracle Corporation and/or its affiliates.
// Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	"context"
	"time"

	v1beta1 "github.com/verrazzano/verrazzano-helidon-app-operator/pkg/apis/verrazzano/v1beta1"
	scheme "github.com/verrazzano/verrazzano-helidon-app-operator/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// HelidonAppsGetter has a method to return a HelidonAppInterface.
// A group's client should implement this interface.
type HelidonAppsGetter interface {
	HelidonApps(namespace string) HelidonAppInterface
}

// HelidonAppInterface has methods to work with HelidonApp resources.
type HelidonAppInterface interface {
	Create(ctx context.Context, helidonApp *v1beta1.HelidonApp, opts v1.CreateOptions) (*v1beta1.HelidonApp, error)
	Update(ctx context.Context, helidonApp *v1beta1.HelidonApp, opts v1.UpdateOptions) (*v1beta1.HelidonApp, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1beta1.HelidonApp, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1beta1.HelidonAppList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.HelidonApp, err error)
	HelidonAppExpansion
}

// helidonApps implements HelidonAppInterface
type helidonApps struct {
	client rest.Interface
	ns     string
}

// newHelidonApps returns a HelidonApps
func newHelidonApps(c *VerrazzanoV1beta1Client, namespace string) *helidonApps {
	return &helidonApps{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the helidonApp, and returns the corresponding helidonApp object, and an error if there is any.
func (c *helidonApps) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta1.HelidonApp, err error) {
	result = &v1beta1.HelidonApp{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("helidonapps").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of HelidonApps that match those selectors.
func (c *helidonApps) List(ctx context.Context, opts v1.ListOptions) (result *v1beta1.HelidonAppList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1beta1.HelidonAppList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("helidonapps").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested helidonApps.
func (c *helidonApps) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("helidonapps").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a helidonApp and creates it.  Returns the server's representation of the helidonApp, and an error, if there is any.
func (c *helidonApps) Create(ctx context.Context, helidonApp *v1beta1.HelidonApp, opts v1.CreateOptions) (result *v1beta1.HelidonApp, err error) {
	result = &v1beta1.HelidonApp{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("helidonapps").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(helidonApp).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a helidonApp and updates it. Returns the server's representation of the helidonApp, and an error, if there is any.
func (c *helidonApps) Update(ctx context.Context, helidonApp *v1beta1.HelidonApp, opts v1.UpdateOptions) (result *v1beta1.HelidonApp, err error) {
	result = &v1beta1.HelidonApp{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("helidonapps").
		Name(helidonApp.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(helidonApp).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the helidonApp and deletes it. Returns an error if one occurs.
func (c *helidonApps) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("helidonapps").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *helidonApps) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("helidonapps").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched helidonApp.
func (c *helidonApps) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.HelidonApp, err error) {
	result = &v1beta1.HelidonApp{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("helidonapps").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
