// Copyright (c) 2020, Oracle Corporation and/or its affiliates.
// Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	"time"

	v1beta1 "github.com/verrazzano/verrazzano-helidon-app-operator/pkg/apis/verrazzano/v1beta1"
	scheme "github.com/verrazzano/verrazzano-helidon-app-operator/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// HelidonAppsGetter has a method to return a HelidonAppInterface.
// A group's client should implement this interface.
type HelidonAppsGetter interface {
	HelidonApps(namespace string) HelidonAppInterface
}

// HelidonAppInterface has methods to work with HelidonApp resources.
type HelidonAppInterface interface {
	Create(*v1beta1.HelidonApp) (*v1beta1.HelidonApp, error)
	Update(*v1beta1.HelidonApp) (*v1beta1.HelidonApp, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1beta1.HelidonApp, error)
	List(opts v1.ListOptions) (*v1beta1.HelidonAppList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.HelidonApp, err error)
	HelidonAppExpansion
}

// helidonApps implements HelidonAppInterface
type helidonApps struct {
	client rest.Interface
	ns     string
}

// newHelidonApps returns a HelidonApps
func newHelidonApps(c *VerrazzanoV1beta1Client, namespace string) *helidonApps {
	return &helidonApps{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the helidonApp, and returns the corresponding helidonApp object, and an error if there is any.
func (c *helidonApps) Get(name string, options v1.GetOptions) (result *v1beta1.HelidonApp, err error) {
	result = &v1beta1.HelidonApp{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("helidonapps").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of HelidonApps that match those selectors.
func (c *helidonApps) List(opts v1.ListOptions) (result *v1beta1.HelidonAppList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1beta1.HelidonAppList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("helidonapps").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested helidonApps.
func (c *helidonApps) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("helidonapps").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a helidonApp and creates it.  Returns the server's representation of the helidonApp, and an error, if there is any.
func (c *helidonApps) Create(helidonApp *v1beta1.HelidonApp) (result *v1beta1.HelidonApp, err error) {
	result = &v1beta1.HelidonApp{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("helidonapps").
		Body(helidonApp).
		Do().
		Into(result)
	return
}

// Update takes the representation of a helidonApp and updates it. Returns the server's representation of the helidonApp, and an error, if there is any.
func (c *helidonApps) Update(helidonApp *v1beta1.HelidonApp) (result *v1beta1.HelidonApp, err error) {
	result = &v1beta1.HelidonApp{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("helidonapps").
		Name(helidonApp.Name).
		Body(helidonApp).
		Do().
		Into(result)
	return
}

// Delete takes name of the helidonApp and deletes it. Returns an error if one occurs.
func (c *helidonApps) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("helidonapps").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *helidonApps) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("helidonapps").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched helidonApp.
func (c *helidonApps) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.HelidonApp, err error) {
	result = &v1beta1.HelidonApp{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("helidonapps").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
