// Copyright (c) 2020, Oracle Corporation and/or its affiliates.
// Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	v1beta1 "github.com/verrazzano/verrazzano-helidon-app-operator/pkg/apis/verrazzano/v1beta1"
	"github.com/verrazzano/verrazzano-helidon-app-operator/pkg/client/clientset/versioned/scheme"
	rest "k8s.io/client-go/rest"
)

type VerrazzanoV1beta1Interface interface {
	RESTClient() rest.Interface
	HelidonAppsGetter
}

// VerrazzanoV1beta1Client is used to interact with features provided by the verrazzano.io group.
type VerrazzanoV1beta1Client struct {
	restClient rest.Interface
}

func (c *VerrazzanoV1beta1Client) HelidonApps(namespace string) HelidonAppInterface {
	return newHelidonApps(c, namespace)
}

// NewForConfig creates a new VerrazzanoV1beta1Client for the given config.
func NewForConfig(c *rest.Config) (*VerrazzanoV1beta1Client, error) {
	config := *c
	if err := setConfigDefaults(&config); err != nil {
		return nil, err
	}
	client, err := rest.RESTClientFor(&config)
	if err != nil {
		return nil, err
	}
	return &VerrazzanoV1beta1Client{client}, nil
}

// NewForConfigOrDie creates a new VerrazzanoV1beta1Client for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *VerrazzanoV1beta1Client {
	client, err := NewForConfig(c)
	if err != nil {
		panic(err)
	}
	return client
}

// New creates a new VerrazzanoV1beta1Client for the given RESTClient.
func New(c rest.Interface) *VerrazzanoV1beta1Client {
	return &VerrazzanoV1beta1Client{c}
}

func setConfigDefaults(config *rest.Config) error {
	gv := v1beta1.SchemeGroupVersion
	config.GroupVersion = &gv
	config.APIPath = "/apis"
	config.NegotiatedSerializer = scheme.Codecs.WithoutConversion()

	if config.UserAgent == "" {
		config.UserAgent = rest.DefaultKubernetesUserAgent()
	}

	return nil
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *VerrazzanoV1beta1Client) RESTClient() rest.Interface {
	if c == nil {
		return nil
	}
	return c.restClient
}
